server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-microservice
          uri: lb://user-microservice
          predicates:
            - Path=/users/**
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/cars/**
        - id: bike-service
          uri: lb://bike-service
          predicates:
            - Path=/bikes/**
        