server:
    port: 8001

spring:
    cloud:
        config:
            server:
                git:
                    default-label: Eureka
                    uri: https://github.com/LenninHuaman/MicroserviceCourse
                    search-paths: config-data
    application:
        name: config-server

